repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: node
        files: ^src/.*\.js$
        types: [javascript]
        additional_dependencies:
          - eslint@10.5.0

      - id: prettier
        name: prettier
        entry: prettier --check
        language: node
        files: ^src/.*\.(js|json)$
        additional_dependencies:
          - prettier@3.8.4
